# Generated by Django 4.1.6 on 2025-05-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
