# Generated by Django 4.1.6 on 2025-05-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0002_alter_perfil_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='color_perfil',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_portada',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_portada/'),
        ),
    ]
