# Generated by Django 4.1.6 on 2025-05-13 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0003_perfil_color_perfil_perfil_foto_portada'),
        ('Publicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='perfil_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones_enviadas', to='Perfil.perfil'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_publicacion/'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='perfil_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_recibidas', to='Perfil.perfil'),
        ),
    ]
