# Generated by Django 4.1.6 on 2025-05-08 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categoria', '0001_initial'),
        ('Grupo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Categoria.categoria')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupo.grupo')),
            ],
        ),
    ]
