# Generated by Django 4.1.6 on 2025-05-08 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Premio', '0001_initial'),
        ('Perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_nominado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Perfil.perfil')),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Premio.premio')),
            ],
        ),
    ]
