# Generated by Django 4.1.6 on 2025-05-15 04:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0004_alter_perfil_color_perfil'),
        ('Nominacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominacion',
            name='perfil_nominado',
        ),
        migrations.AddField(
            model_name='nominacion',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='nominacion',
            name='perfil_creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominaciones_creadas', to='Perfil.perfil'),
        ),
        migrations.AddField(
            model_name='nominacion',
            name='perfiles_nominados',
            field=models.ManyToManyField(to='Perfil.perfil'),
        ),
    ]
