# Generated by Django 4.1.6 on 2025-05-08 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='voto',
            table=None,
        ),
    ]
