# Generated by Django 4.1.6 on 2025-05-15 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Votacion', '0001_initial'),
        ('Perfil', '0004_alter_perfil_color_perfil'),
        ('Voto', '0002_alter_voto_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voto',
            name='premio',
        ),
        migrations.AddField(
            model_name='voto',
            name='perfil_emisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votos_emitidos', to='Perfil.perfil'),
        ),
        migrations.AddField(
            model_name='voto',
            name='votacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Votacion.votacion'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='perfil_votado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votos_recibidos', to='Perfil.perfil'),
        ),
    ]
