# Generated by Django 4.1.6 on 2025-05-17 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Perfil', '0004_alter_perfil_color_perfil'),
        ('Premio', '0001_initial'),
        ('Votacion', '0002_alter_votacion_fecha_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiosGanados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medalla', models.CharField(max_length=255)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Perfil.perfil')),
                ('premio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Premio.premio')),
                ('votacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Votacion.votacion')),
            ],
        ),
    ]
