# Generated by Django 4.1.6 on 2025-05-17 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PremiosGanados', '0002_remove_premiosganados_votacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiosganados',
            name='fecha_ganado',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 17, 9, 4, 15, 633906, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
