# Generated by Django 4.1.6 on 2025-05-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grupo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='codigo_acceso',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
