# Generated by Django 4.1.6 on 2025-05-15 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Premio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Premio.premio')),
            ],
        ),
    ]
