# Generated by Django 4.1.6 on 2025-05-16 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Votacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacion',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
