# Generated by Django 4.1.6 on 2025-05-13 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0003_perfil_color_perfil_perfil_foto_portada'),
        ('Comentario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='remitente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Perfil.perfil'),
        ),
    ]
